name: CI/CD Boncuk

on:
  push:
    branches: [ master, dev, feature/*, hotfix/*, release/* ]
  pull_request:
    branches: [ master, dev, feature/*, hotfix/*, release/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore Boncuk.sln
    - name: Build
      working-directory: ./src
      run: dotnet build Boncuk.sln --no-restore
    - name: Test
      working-directory: ./src
      run: dotnet test Boncuk.sln --no-build --verbosity normal
